import type { Metadata } from "next";
import { Geist, Geist_Mono,Cinzel_Decorative,Raleway,Passions_Conflict } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const CinzelDecorative = Cinzel_Decorative({
  subsets: ['latin'],
  weight: ['700' ], 
  variable: '--font-cinzel',
});

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
  variable: '--font-raleway',
});

const passionsConflict =Passions_Conflict({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-passions-conflict',
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
